name: introduced for test purposes only with further development on another branch

on:
  workflow_dispatch:

jobs:
  NPM_dist_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Correct security dist-tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CARBON_BOT_NPM_TOKEN }}
        run:
          bash .github/scripts/release-disttag-update.sh packages/security
          @carbon/ibm-security

      - name: Correct CDAI dist-tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CARBON_BOT_NPM_TOKEN }}
        run:
          bash .github/scripts/release-disttag-update.sh packages/cdai
          @carbon/ibm-cloud-cognitive-cdai

